### PR TITLE
Add support of stroke-dasharray

### PR DESCRIPTION
**Pull request by bcomb**
Split the path before sending it to the rasterizer.
This code is just an adaptation of code from https://github.com/Samsung/rlottie

### CODE REVIEW

**Comment by bcomb** [comment]
Hi in order to test my functionnality, i suggest you to also compile the test.cpp example.
In this test i generate (svg+png) for Line/Curve/BezierCurve/Arc/QuadraticCurve with different dashing configuration.

I also find a bug with "transparent" color that lead to black filled polygon fe6f848

**Comment by sammycage** [comment]
Interesting :-) but transparent is not part of SVG 1.1 standard colors : https://github.com/sammycage/lunasvg/commit/fe6f848a84ad9cbe17cdd6f7d1594665d265d6a2

**Comment by bcomb** [comment]
For the 3495285, i write a minimal test that show the problem

`void wrong_rendering()
{
    const char* tests[] =
    {
    R"svg(
<svg xmlns="http://www.w3.org/2000/svg" version="1.2" baseProfile="tiny" width="104" height="64" viewBox="-4 36 208 128">
<path d="M 0,155 200,45 M 0,45 200,155" stroke-width="4" stroke="rgb(255, 255, 128)" fill="none" ></path>
</svg>
    )svg"
,
    R"svg(
<svg xmlns="http://www.w3.org/2000/svg" width="25" height="50">
<path d="M 0,15 L 5,15 L 5,5 L 25,25 L 5,45 L 5,35 L 0,35" fill="none" stroke="rgb(255, 255, 128)" stroke-width="2" />
</svg>
    )svg"
    };


    const bool reuse = true;
    const int tests_count = sizeof(tests) / sizeof(tests[0]);
    SVGDocument share_doc;
    for (int i = 0; i < tests_count; ++i)
    {
        SVGDocument new_doc;
        SVGDocument& doc = reuse ? share_doc : new_doc;

        bool test_success = doc.loadFromData(tests[i]);
        if (test_success)
        {
            Bitmap lBitmap = doc.renderToBitmap();
            test_success = test_success && lBitmap.width() != 0;
            char tmp_name[64];
            sprintf(tmp_name, "%03d.png", i);
            test_success = test_success && stbi_write_png(tmp_name, lBitmap.width(), lBitmap.height(), 4, lBitmap.data(), 0);
        }
    }
}`

**Comment by bcomb** [comment]
[wrong_rendering.txt](https://github.com/sammycage/lunasvg/files/5541286/wrong_rendering.txt)

**Pull request closed without merging**
